#!/bin/bash

set -e
cmd=$1; shift

modify_netconfig()
{
	local resolv_file=$1
	local service=$2
	local intf=$3
	echo "resolv_file=${resolv_file} service=${service} intf=${intf}"
	local dnsservers=""
	local dnssearch=""
	dnsservers=(`awk -- '/nameserver/ {printf "%s ", $2}' < $resolv_file 2>/dev/null`)
	dnssearch=(`awk -- '/search/ {for (i=2; i<=NF; i++) printf $i}' < $resolv_file 2>/dev/null`)
	{
		echo "DNSSEARCH='${dnssearch[*]}'"
		echo "DNSSERVERS='${dnsservers[*]}'"
	} | /sbin/netconfig modify -s "$service" -i "$intf"
}

remove_netconfig()
{
	local service=$1
	local intf=$2
	/sbin/netconfig remove -s "$service" -i "$intf"
}

case $cmd in
backup)
	# Back up the existing resolv.conf file
	echo "TODO: NO BACKUP TO PERFORM YET"
	: ;;

restore)
	echo "TODO: REPLACE WITH REMOVE CMD"
	filename="null"
	intf="eth0"	# FIXME by passing correct params from update.c
	restore="yes"
	modify_netconfig $filename $restore $intf
	: ;;

install)
	echo "INSTALL: $@"
	filename=$1
	service=$2
	intf=$3
	modify_netconfig $filename $service $intf
	: ;;

remove)
	echo "REMOVE: $@"
	service=$1
	intf=$2
	remove_netconfig $service $intf
	: ;;

*)
	echo "$0: command $cmd not supported" >&2
	exit 1;;
esac
