#!/bin/bash

set -e
cmd=$1; shift

modify_netconfig()
{
	local resolv_file=$1
	local restore=$2
	local service=$3
	local intf=$4
	echo "resolv_file=${resolv_file} restore=${restore} intf=${intf}"
	local dnsservers=""
	local dnssearch=""
	if [ "$restore" = "no" ]
	then
		dnsservers=`grep "nameserver" $resolv_file | awk '{printf "%s ", $2}'`
		dnssearch=`grep "search" $resolv_file | awk '{for (i=2; i<=NF; i++) print $i}'`
	fi
	{
		echo "DNSSEARCH='$dnssearch'"
		echo "DNSSERVERS='$dnsservers'"
	} | /sbin/netconfig modify -s "$service" -i "$intf"
}

remove_netconfig()
{
	local service=$1
	local intf=$2
	/sbin/netconfig remove -s "$service" -i "$intf"
}

case $cmd in
backup)
	# Back up the existing resolv.conf file
	echo "TODO: NO BACKUP TO PERFORM YET"
	: ;;

restore)
	echo "TODO: REPLACE WITH REMOVE CMD"
	filename="null"
	intf="eth0"	# FIXME by passing correct params from update.c
	restore="yes"
	modify_netconfig $filename $restore $intf
	: ;;

install)
	echo "INSTALL: $@"
	filename=$1
	service=$2
	intf=$3
	restore="no"
	modify_netconfig $filename $restore $service $intf
	: ;;

remove)
	echo "REMOVE: $@"
	service=$1
	intf=$2
	remove_netconfig $service $intf
	: ;;

*)
	echo "$0: command $cmd not supported" >&2
	exit 1;;
esac
