#!/bin/bash

set -e
umask 077

scriptname=$0
scriptdir=`dirname $0`
if [ -f "$scriptdir/functions" ]; then
	. "$scriptdir/functions"
fi

##################################################################
# Generate an openvpn config file from the XML data we've been
# given.
# It'd be tempting to do this with xsltproc, except that we need
# to take care of incomplete auth information (and have the client
# prompt for it), as well as copying the temporary key and cert files
# to a permanent location.
##################################################################
function openvpn_update_config {

	conffile="$confdir/config"
	cat <<EOF
client
persist-key
persist-tun
nobind
comp-lzo
explicit-exit-notify 5
EOF

	echo "dev $WICKED_INTERFACE_NAME"

	wicked_getargs 'authreq=%{config/auth/require}' 'user=%{config/auth/user}' 'pass=%{config/auth/password}'
	if [ "$authreq" = "true" ]; then
		echo "auth-user-pass $confdir/auth"

		if [ -z "$user" ]; then
			wicked_auth_error "auth.user|USER|user name for openvpn connection"
		fi
		if [ -z "$pass" ]; then
			wicked_auth_error "auth.password|PASSWORD|password for openvpn connection (user $user)"
		fi

		(
			echo "$user"
			echo "$pass"
		) >"$confdir/auth"
	fi

	wicked_getargs 'address=%{config/remote-address}' 'port=%{config/remote-port}' 'protocol=%{config/protocol}'
	if [ -n "$address" ]; then
		echo "remote $address"
	fi
	if [ -n "$port" ]; then
		echo "port $port"
	fi
	if [ -n "$protocol" ]; then
		echo "proto $protocol"
	fi

	rm -f $confdir/*.pem
	wicked_getargs 'tls_ca_cert=%{config/tls/ca-cert}' 'tls_client_cert=%{config/tls/client-cert}' 'tls_client_key=%{config/tls/client-key}'

	if [ -n "$tls_ca_cert" ]; then
		cp "$tls_ca_cert" $confdir/ca-cert.pem
		echo "ns-cert-type server"
		echo "ca $confdir/ca-cert.pem"
	fi
	if [ -n "$tls_client_cert" ]; then
		cp "$tls_client_cert" $confdir/client-cert.pem
		echo "cert $confdir/client-cert.pem"
	fi
	if [ -n "$tls_client_key" ]; then
		cp "$tls_client_key" $confdir/client-key.pem
		echo "key $confdir/client-key.pem"
	fi

	# Attention: add a script callback that notifies us when the link and addresses come up
	echo "up \"$scriptname network-up-notify $WICKED_TUNNEL_ID\""
}

##################################################################
# When the network has been brought up by openvpn, we're being
# called back through the --up hook.
# Build an addrconf lease.
##################################################################
function openvpn_build_lease {

	filename=$1

	wicked lease $filename set --state granted
	wicked lease $filename add --address $ifconfig_local/32 --peer $ifconfig_remote

	for n in ${!route_network_*}; do
		index=${n//route_network_}
		for var in network netmask gateway; do
			eval $var=\$route_${var}_${index}
		done

		wicked lease $filename add --route $network --netmask $netmask --gateway $gateway
	done
}

# Check if we're being called back from openvpn
if [ "$1" = "network-up-notify" ]; then
	WICKED_TUNNEL_ID=$2
	shift 2

	confdir=/var/run/wicked/$WICKED_TUNNEL_ID
	mkdir -m 700 -p $confdir
	openvpn_build_lease $confdir/lease

	exit 0
fi

if [ -z "$WICKED_TUNNEL_ID" ]; then
	echo "$0: no tunnel-id" >&2
	exit 1
fi

confdir=/var/run/wicked/$WICKED_TUNNEL_ID
mkdir -m 700 -p $confdir

cmd=$1; shift
case $cmd in
change)
	openvpn_update_config >$confdir/config
	: ;;

link-up)
	rm -f $confdir/lease

	/usr/sbin/openvpn --daemon $WICKED_TUNNEL_ID --writepid $confdir/pid --config $confdir/config --cd /etc/openvpn >/dev/null 2>&1 3>&1

	# retries is in 10th of a second
	retries=100
	while [ ! -f $confdir/lease ]; do
		if [ $retries -lt 0 ]; then
			wicked_error "Timed out waiting for tunnel to come up"
		fi

		usleep 500000
		let retries-=5
	done

	# Now inform wickedd about the lease
	wicked lease $confdir/lease install --device $WICKED_OBJECT_PATH
	: ;;

link-down)
	pidfile=$confdir/pid
	if [ -f $pidfile ]; then
		date
		if ! killproc -p $pidfile /usr/sbin/openvpn; then
			date
			wicked_error "Error shutting down openvpn daemon for tunnel $WICKED_TUNNEL_ID"
		fi
		date
	fi
	: ;;
esac
