

#ifndef ETHERTYPE_LLDP
# define ETHERTYPE_LLDP		0x88CC
#endif

enum ni_lldp_basic_tlv {
	NI_LLDP_TLV_END		= 0,
	NI_LLDP_TLV_CHASSIS_ID	= 1,
	NI_LLDP_TLV_PORT_ID	= 2,
	NI_LLDP_TLV_TTL		= 3,
	NI_LLDP_TLV_PORT_DESC	= 4,
	NI_LLDP_TLV_SYSTEM_NAME	= 5,
	NI_LLDP_TLV_SYSTEM_DESC	= 6,
	NI_LLDP_TLV_SYSTEM_CAPS	= 7,
	NI_LLDP_TLV_MGMT_ADDR	= 8,

	NI_LLDP_TLV_ORGSPEC	= 127,
};
